from typing import Optional

from pydantic import BaseModel, Field


class ErrorDetails(BaseModel):
    """
        Details format for errors according to the RFC 7807. thr RFC is for http but
        can be also used to describe none http errors in a structured format.
    """
    type: str = Field(
        description="A URI reference that identifies the problem type."
    )
    title: str = Field(
        description="A short, human-readable summary of the problem type."
    )
    status: int = Field(
        description="The HTTP status code generated by the origin server "
                    "for this occurrence of the problem."
    )
    detail: Optional[str] = Field(
        description="A human-readable explanation "
                    "specific to this occurrence of the problem."
    )
    instance: Optional[str] = Field(
        description="A URI reference that identifies the specific occurrence"
                    " of the problem.",
        default=None
    )

    @staticmethod
    def create_as_dict_with_extending_fields(
            type: str,
            title: str,
            status: int,
            detail: str = None,
            instance: str = None,
            **extending_fields
    ) -> dict:
        error_details_dict = ErrorDetails(
            type=type,
            title=title,
            status=status,
            detail=detail,
            instance=instance
        ).model_dump(exclude_none=True)

        if any(
                (extending_key in error_details_dict.keys())
                for extending_key in extending_fields.keys()
        ):
            raise ValueError("One of the extending parameters is overriding base ErrorDetails field.")

        error_details_dict.update(**extending_fields)

        return error_details_dict