from typing import Optional

from pydantic import BaseModel, Field


class ErrorDetails(BaseModel):
    """
        Details format for errors according to the RFC 7807. thr RFC is for http but
        can be also used to describe none http errors in a structured format.
    """
    type: str = Field(
        description="A URI reference that identifies the problem type."
    )
    title: str = Field(
        description="A short, human-readable summary of the problem type."
    )
    status: int = Field(
        description="The HTTP status code generated by the origin server "
                    "for this occurrence of the problem."
    )
    detail: Optional[str] = Field(
        description="A human-readable explanation "
                    "specific to this occurrence of the problem."
    )
    instance: Optional[str] = Field(
        description="A URI reference that identifies the specific occurrence"
                    " of the problem.",
        default=None
    )
